# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TEAM SSAFY.HAPPY
email: j.1star.0726@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Hello, SSAFY!</h3><h1>SSAFY.HAPPY DevJournal</h1><h3>Awesome TEAM SSAFY.HAPPY Post for Developers!</h3>Hope you like it!"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hemangsk.github.io" # the base hostname & protocol for your site
twitter_username: J1STAR
github_username:  J1STAR

# Build settings
markdown: kramdown
